import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'

export default function Home() {
  return (
    <>
     <Header/>
    <div className={styles.container}>
      <Head>
        <title>Sarim Hassan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sarim Hassan
        </h1>

        <p className={styles.description}>
          I'm a Developer, who likes Desiging, Writing and 
          Building Open Source Projects
          {/* <code className={styles.code}>pages/index.js</code> */}
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
            </div>
        </div>
      </main>

      <footer className={styles.footer}>
          Made with ♥ by Sarim{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
      </footer>
    </div>
    </>
  )
}
